---
name: Dependabot Auto-Approve
# yamllint disable-line rule:truthy
on:
  # run when a PR is opened or updated to main
  pull_request:
    branches: ["main"]

permissions:
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@8348ea7f5d949b08c7f125a44b569c9626b05db3 # v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Approve a PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
