---
name: Pull Request Labeler

# yamllint disable-line rule:truthy
on:
  # zizmor: ignore[dangerous-triggers] This is safe because we are not running any untrusted code
  # and setting minimal permissions required.
  - pull_request_target 

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          # automatically add labels to pull requests based on the files changed
          configuration-path: .github/pr-labeler.yml
